apiVersion: v1
kind: Service
metadata:
  name: saas-tycoon-client
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.port }}
  selector:
    app: saas-tycoon-client