apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-tycoon-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-tycoon-client
  template:
    metadata:
      labels:
        app: saas-tycoon-client
    spec:
      containers:
        - name: client
          image: {{ .Values.client.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.client.port }}
          env:
            - name: NODE_ENV
              value: {{ .Values.client.env.NODE_ENV }}
            - name: API_URL
              value: {{ .Values.client.config.API_URL }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "250m"
