apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-tycoon-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-tycoon-server
  template:
    metadata:
      labels:
        app: saas-tycoon-server
    spec:
      containers:
        - name: server
          image: {{ .Values.server.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
            - name: admin-http
              containerPort: {{ .Values.server.adminPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.server.metricsPort }}
              protocol: TCP
          env:
            - name: MONGO_URI
              value: "mongodb://{{ .Values.mongo.username }}:{{ .Values.mongo.password }}@mongo:{{ .Values.mongo.port }}/{{ .Values.mongo.database }}?authSource=admin"
            - name: NODE_ENV
              value: {{ .Values.server.env.NODE_ENV }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"