name: Build and Push Docker Images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  packages: write
jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./saas-tycoon-server
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./saas-tycoon-server
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/saas-tycoon-server:latest

  build-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./saas_tycoon_client
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./saas_tycoon_client
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/saas-tycoon-client:latest